### PR TITLE
Add a changelog

### PR DESCRIPTION
**Pull request by awharn**
Signed-off-by: Andrew W. Harn <andrew.harn@broadcom.com>

### CODE REVIEW

**Review by zFernand0 — APPROVED** [review]
This looks awesome! `< ( ^ - ^ ) >`

**Review by zFernand0 — APPROVED** [review]
Thanks for adding the changelog and updating the contributing.md file
`< ( ^ - ^ ) >`

**Comment by zFernand0** [comment]
@tjohnsonBCM, @awharn, Meybe we don't need to mentions all the details (like updating snapshots) in the future?
Just things that have end-user impact?
Just a thought

**Comment by awharn** [comment]
Agreed. Just got caught up looking in the Git history for information to put in. :)

**Pull request merged**
