### PR TITLE
Change URL from /apis to /api to allow matching to v1 conformance and the IMS Operations API

### PR DESCRIPTION
**Pull request by Joe-Winchester**
Signed-off-by: Joe-Winchester <winchest@uk.ibm.com>

fixes #24

### CODE REVIEW

**Review by zFernand0 — APPROVED** [review]

**Comment by zFernand0** [comment]
@Joe-Winchester, thoughts on this?

**Comment by Joe-Winchester** [comment]
@zFernand0 - tks for the nudge.  We should push this into master at the same time that the final ims-operations-api package that is submitted for Zowe v1 conformance occurs as the two go hand in hand.  I did start a while back on v1 conformance and saw a few places where it wouldn't have passed, so I am working to get them fixed up.  I'll try to get work on this next week and might need to reach out for help as I ran into some build issues with the ops api.  I'll update this issue and try to join scrums next week to update on progress.  Tks !

**Comment by t1m0thyj** [comment]
@Joe-Winchester Should we include this change in the upcoming `@zowe-v2-lts` version of the IMS plug-in?

**Comment by Joe-Winchester** [comment]
Hi @t1m0thyj ,   I think this change is already done in the IMS Operations API.   Looking at https://github.com/zowe/ims-operations-api/blob/d7daf47bd52ff3a9c7e35f939caf835fdcdbac7e/ims/src/main/resources/application.yml#L32 is uses `api/v1` already.     
I'm not sure we need to switch this to v2, as although Zowe itself is changing to v2, the IMS Ops API are remaining unchanged so there is no need to reversion them.
At a side note, there is a customer issue https://github.com/zowe/ims-operations-api/issues/21 which is where the IMS Operations API fail to load because of a recent change in the Zowe launcher.   I think we should fix this and also then look to add some automated build and test to avoid regression and then get a v2 conformance badge, although there is an issue about which squad should do this and who has overall ownership of the IMS Operations API repo.

**Comment by zFernand0** [comment]
I believe the change in question is to change the URL used by the plugin from `/ims/apis/v1/` to `/ims/api/v1/`.
If we still want to do that, we should do it against next 😋

**Pull request merged**
